before_script:
  - python3.7 --version
  - pip3.7 -V
  - python3.7 -m venv ENV
  - source ENV/bin/activate

stages:
  - test

test:
  stage: test
  script:
  - pip3.7 install -r requirements.txt
  - pip3.7 install coverage
  - pip3.7 install django-nose
  - python3.7 manage.py test viewer.tests.test_internal
  - pip3.7 install flake8==3.7.8
  - pip3.7 install mypy==0.720
  - flake8 --ignore="E501,E402,F401,W503,F811" --exclude="migrations,ENV,venv,src,.mypy_cache" .
  - mypy . --ignore-missing-imports --strict-equality
  cache:
    paths:
    - .mypy_cache
  tags:
    - django
