before_script:
  - python3.6 --version
  - pip3.6 -V
  - virtualenv --version
  - virtualenv -p python3.6 ENV
  - source ENV/bin/activate

stages:
  - test

test:
  stage: test
  script:
  - pip3.6 install -r requirements.txt
  - python3.6 manage.py test viewer.tests.test_internal
  - pip3.6 install flake8
  - flake8 --ignore="E501,E402" --exclude="migrations,ENV,src" .
  tags:
    - django
